use_frameworks!

platform :ios, '8.0'

target 'MineModual_Example' do
  pod 'MineModual', :path => '../'

  target 'MineModual_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
